---
title: "Breast Cancer Study"
output: rmarkdown::github_document
---
```{r, echo = FALSE}
knitr::opts_chunk$set(
  fig.path = "README_figs/README-"
)
```

Libraries
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(randomForest)
library(ROCR)
library(e1071)
```


Load data
```{r message=FALSE, warning=FALSE}
setwd("D:\\University\\Study Materials\\Spring Semester\\Data Mining 1\\Final Project")
breastcancer = read_csv('breast-cancer-wisconsin-data.csv')[,1:32]
```

Data Preparation

```{r}
breastcancer = breastcancer %>%
  mutate(diagnosis = as.factor(diagnosis))

colnames(breastcancer)
colnames(breastcancer)[10] = "concave_points_mean" 
colnames(breastcancer)[20] = "concave_points_se" 
colnames(breastcancer)[30] = "concave_points_worst" 

str(breastcancer)
table(breastcancer$diagnosis)

sum(is.na(breastcancer))   # no missing value

dim(breastcancer)
```

EDA

```{r}
ggplot(breastcancer, aes(x = diagnosis, fill = diagnosis)) +
  geom_bar() +
  labs(title = 'Number of Benign v.s. Malignant')

  
feature_names = names(breastcancer)[3:32]

breastcancer %>%
  select(c('diagnosis', feature_names)) %>%
  pivot_longer(cols = feature_names) %>%
  ggplot(aes(x = value)) +
  geom_density(aes(fill = diagnosis), alpha = 0.5) +
  facet_wrap(~name, scales = 'free') +
  labs(title = 'Variable Density Plot',
       subtitle = 'by Diagnosis',
       x = '', y = 'density') +
  theme(axis.text.y = element_blank())
```

#outlier analysis
#correlation analysis

Supervised Learning

train-test split

```{r}
set.seed(7047)
idx = sample(1:nrow(breastcancer), nrow(breastcancer)*0.75)

bcancer = breastcancer[,-1]

bcancer_train = bcancer[idx,]
bcancer_test = bcancer[-idx,]
```

random-forest

m = sqrt(p) = 6

```{r}
cancer_rf = randomForest(diagnosis~., data = bcancer_train, mtry = 6)
cancer_rf

# define cost function

cost_auc = function(prob, obs) {
  pred = prediction(prob, obs)
  perf = performance(pred, "tpr", "fpr")
  cost = slot(performance(pred, "auc"), "y.values")[[1]]
  
  return(cost)
}

#in-sample AUC
cancer_rf_prob_train = predict(cancer_rf, type = "prob")[,2]
cost_auc(cancer_rf_prob_train, bcancer_train$diagnosis)

#out-of-sample AUC
cancer_rf_prob_test = predict(cancer_rf, newdata = bcancer_test,type = "prob")[,2]
cost_auc(cancer_rf_prob_test, bcancer_test$diagnosis)

```

SVM

```{r}
cancer_svm = svm(diagnosis ~ ., data = bcancer_train)

# in-sample
pred_svm_train =  predict(cancer_svm)
table(pred_svm_train, bcancer_train$diagnosis)
mean(pred_svm_train != bcancer_train$diagnosis)


# out-of-sample 
pred_svm_test  =  predict(cancer_svm, bcancer_test)
table(pred_svm_test, bcancer_test$diagnosis)
mean(pred_svm_test != bcancer_test$diagnosis)
```