---
title: "R Notebook"
output: html_notebook
---

```{r}
setwd("D:\\University\\Study Materials\\Spring Semester\\Data Mining 1\\Final Project")
breastcancer = read_csv('Pdata.csv')[,1:32]
```
```{r}
head(breastcancer)
pca_data = breastcancer[,-c(1,2)]
head(pca_data)
rownames(pca_data) = breastcancer$id
```

```{r}
pca = prcomp(t(pca_data),scale= TRUE)
pca = prcomp(t(pca_data_s),scale= TRUE) # Test after scaling 
```


```{r}
plot(pca$x[,1],pca$x[,2])
```

PCA variation plot

```{r}
pca.var = pca$sdev^2
pca.var.per = round(pca.var/sum(pca.var)*100,1)
barplot(pca.var.per, main="Scree Plot")
```

```{r}
pca_data_gg = data.frame(Sample=rownames(pca$x),
                         X = pca$x[,1],
                         Y = pca$x[,2]) 
head(pca_data_gg)

library(ggplot2)
ggplot(data=pca_data_gg, aes(x=X, y=Y, label=Sample))+
  geom_text()+
  xlab(pca.var.per[1])+
  ylab(pca.var.per[2])+
  theme_bw()+
  ggtitle("PCA Graph")
```

Loading Scores

```{r}
loading_scor/es = (pca$rotation[,1])
gene_scores = abs(loading_scores)
gene_score_ranked = sort(gene_scores,decreasing = TRUE)
top10_gene = names(gene_score_ranked[1:10])
top10_gene

pca$rotation[top10_gene,1]
```

```{r}
typeof(pca)
```

############## Centering the Data

```{r}
pca_data_s = scale(pca_data)
summary(pca_data_s)
```

